# Generated by Django 4.2.4 on 2023-08-11 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('typecard', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=200)),
                ('dateofbrith', models.CharField(max_length=30)),
                ('haircolor', models.CharField(max_length=50)),
                ('eyecolor', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('birthcertificate', models.CharField(max_length=200)),
                ('du', models.CharField(max_length=20)),
                ('docnumber', models.CharField(max_length=200)),
                ('expiry', models.CharField(max_length=20)),
                ('placeofissue', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
