# Generated by Django 4.2.4 on 2023-08-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcard',
            old_name='dateofbrith',
            new_name='dateofbirth',
        ),
    ]
